# Generated by Django 3.2.1 on 2021-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='object_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
