# Generated by Django 3.2.1 on 2021-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='currency',
            field=models.CharField(default='EUR', max_length=255),
        ),
    ]
