# Generated by Django 3.2.1 on 2021-09-08 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0002_alter_address_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('parcel_length', models.DecimalField(decimal_places=3, max_digits=3)),
                ('parcel_width', models.DecimalField(decimal_places=3, max_digits=3)),
                ('parcel_weight', models.DecimalField(decimal_places=3, max_digits=3)),
                ('parcel_height', models.DecimalField(decimal_places=3, max_digits=3)),
                ('distance_unit', models.CharField(max_length=255)),
                ('mass_unit', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_from', to='shippings.address')),
                ('address_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_to', to='shippings.address')),
                ('parcels', models.ManyToManyField(to='shippings.Parcel')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('carrier_account', models.CharField(max_length=255)),
                ('servicelevel_token', models.CharField(max_length=255)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.shipment')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
