# Generated by Django 3.2.1 on 2021-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0003_parcel_shipment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
