# Generated by Django 3.2.1 on 2021-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0004_alter_address_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcel_height',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_length',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_width',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
