# Generated by Django 3.2.1 on 2021-09-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0005_auto_20210908_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
