name: CICD Vaanah-Backend

on:
  push:
    branches:
      - feature/test

jobs:
# Test application Image
  test:
#    needs: build-and-push eddy is here
    name: Vaanah Test
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: docker-compose run vaanah-test


