# Generated by Django 3.2.1 on 2021-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210622_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='EUR', max_length=12),
        ),
    ]
