# Generated by Django 3.2.1 on 2021-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
