# Generated by Django 3.2.1 on 2021-06-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20210621_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='name',
        ),
    ]
