# Generated by Django 3.2.1 on 2021-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210528_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')], default='M', max_length=20),
        ),
    ]
