---
- hosts: webservers
  tasks:
  - name: install pip3
    apt:
      update_cache: yes
      name: python3-pip
    become: yes

  - name: Install Docker
    apt:
      name: docker.io
    become: yes

  - name: Start Docker
    shell: |
      systemctl start docker
      systemctl enable docker
    become: yes

  - name: Pull Frontend app locally
    shell: |
      docker pull papeterinnova/vaana-django:latest
    become: yes

  - name: Run Image
    shell: |
      docker run -d -p 8082:8020 papeterinnova/vaana-django:latest
    become: yes
